{"uuid":"4a62d2f6-ec05-486c-88a7-6e67e7bbfaa3","historyId":"f99423a94f07061ba84338fffde90973","fullName":"ru.yandex.practicum.scooter.api.CreateCourierTest.addCourierWithIdenticalLoginError","labels":[{"name":"package","value":"ru.yandex.practicum.scooter.api"},{"name":"testClass","value":"ru.yandex.practicum.scooter.api.CreateCourierTest"},{"name":"testMethod","value":"addCourierWithIdenticalLoginError"},{"name":"suite","value":"ru.yandex.practicum.scooter.api.CreateCourierTest"},{"name":"host","value":"5CD70921SF"},{"name":"thread","value":"17084@5CD70921SF.main(1)"},{"name":"framework","value":"junit4"},{"name":"language","value":"java"},{"name":"story","value":"API для создания курьера"}],"links":[],"name":"Создание курьера. Нельзя создать курьера с неуникальным логином","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected:<...гин уже используется[]> but was:<...гин уже используется[. Попробуйте другой.]>","trace":"org.junit.ComparisonFailure: expected:<...гин уже используется[]> but was:<...гин уже используется[. Попробуйте другой.]>\r\n\tat org.junit.Assert.assertEquals(Assert.java:117)\r\n\tat org.junit.Assert.assertEquals(Assert.java:146)\r\n\tat ru.yandex.practicum.scooter.api.CreateCourierTest.addCourierWithIdenticalLoginError(CreateCourierTest.java:90)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\r\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)\r\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\r\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)\r\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\r\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\r\n\tat org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)\r\n\tat org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)\r\n\tat org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)\r\n\tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)\r\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)\r\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)\r\n\tat org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)\r\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)\r\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)\r\n\tat org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)\r\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)\r\n\tat org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)\r\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:413)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)\r\n"},"stage":"finished","description":"Проверка, что если создать курьера с логином, который уже есть, возвращается ошибка. Проверка реализована согласно документации. По документации текст ошибки \"Этот логин уже используется\", но при проверке через Postman текст ошибки \"Этот логин уже используется. Попробуйте другой.\"","steps":[{"name":"Подготовка тестовых данных курьера","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1656174394083,"stop":1656174394108},{"name":"Добавление курьера","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"Request","source":"69173a65-ee16-4e5a-92b4-c5d17b432856-attachment.html","type":"text/html"},{"name":"HTTP/1.1 201 Created","source":"96f81bb5-55ae-46bc-a04e-f486cd121aa7-attachment.html","type":"text/html"}],"parameters":[{"name":"courierRegistrationData","value":"ru.yandex.practicum.scooter.api.model.RequestCourierRegistrationData@2c306a57"}],"start":1656174394112,"stop":1656174402003},{"name":"Добавление курьера","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"Request","source":"72ff7e5b-429c-4a75-bc08-4db2d83aedea-attachment.html","type":"text/html"},{"name":"HTTP/1.1 409 Conflict","source":"e5a44dc9-0bba-4556-9c13-73c0db4cc8a5-attachment.html","type":"text/html"}],"parameters":[{"name":"courierRegistrationData","value":"ru.yandex.practicum.scooter.api.model.RequestCourierRegistrationData@2336d3f"}],"start":1656174402003,"stop":1656174402324},{"name":"Удаление созданного курьера","status":"passed","stage":"finished","steps":[{"name":"Логин курьера","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"Request","source":"45df20cb-6ce3-4760-9882-c7b8ce7b94aa-attachment.html","type":"text/html"},{"name":"HTTP/1.1 200 OK","source":"058e3aac-b2c3-4227-8e83-9a5923e67d62-attachment.html","type":"text/html"}],"parameters":[{"name":"requestCourierLoginData","value":"ru.yandex.practicum.scooter.api.model.RequestCourierLoginData@74919649"}],"start":1656174402367,"stop":1656174402622},{"name":"Получение id курьера","status":"passed","stage":"finished","steps":[{"name":"Логин курьера","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"Request","source":"74ef853c-d8a6-4bc0-80e8-7a34c38a5821-attachment.html","type":"text/html"},{"name":"HTTP/1.1 200 OK","source":"df514dca-79f4-43f0-8586-58b3b6dbc731-attachment.html","type":"text/html"}],"parameters":[{"name":"requestCourierLoginData","value":"ru.yandex.practicum.scooter.api.model.RequestCourierLoginData@74919649"}],"start":1656174402622,"stop":1656174402844}],"attachments":[],"parameters":[{"name":"requestCourierLoginData","value":"ru.yandex.practicum.scooter.api.model.RequestCourierLoginData@74919649"}],"start":1656174402622,"stop":1656174404584},{"name":"Удаление курьера","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"Request","source":"71444e97-4fd8-4fb0-a1b7-a85c0352d061-attachment.html","type":"text/html"},{"name":"HTTP/1.1 200 OK","source":"0e834685-53d5-4e67-be11-3e723dc5561b-attachment.html","type":"text/html"}],"parameters":[{"name":"courierId","value":"ru.yandex.practicum.scooter.api.model.CourierId@61e34bec"}],"start":1656174404585,"stop":1656174405007}],"attachments":[],"parameters":[],"start":1656174402367,"stop":1656174405007}],"attachments":[],"parameters":[],"start":1656174394021,"stop":1656174405030}